name = "cloudflare-r2-worker"
main = "src/index.js"
compatibility_date = "2023-08-01"
compatibility_flags = ["nodejs_compat"]

# 配置环境变量
[vars]
API_KEY = "sk-proj-xxxx"

# 定义R2存储桶
[[r2_buckets]]
binding = "image"
bucket_name = "image"

[[r2_buckets]]
binding = "file"
bucket_name = "file"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.